### PR TITLE
Adding dleq to v0 crypto

### PR DESCRIPTION
**Pull request by nikkolasg**
This PR brings DLEQ to the v0 branch !

### CODE REVIEW

**Comment by nikkolasg** [comment]
We have troubles with Travis for v0 on crypto ?
I'm starting to like less and less this `gopkg` thing ... !

**Comment by ineiti** [comment]
I don't think it has to do with `gopkg` - it's trying to update the 'normal' `github.com/dedis/crypto` and failing there. Either it's our scripts or some strange git-history that makes it fail.

Can you try to start a clean branch from `v0`?

```
cd $GOPATH/src/github.com/dedis/crypto
git checkout v0
git pull
git checkout -b new_dleq
git checkout dleq_to_v0 .
git commit -am "probably already committed"
git push -u origin new_dleq
```

and then PR that branch?

**Comment by nikkolasg** [comment]
but that's exactly what I did for this PR... :/ Don't you think it's because it can't get the `gopkg.in`onet version to merge with this version for running the tests or stg ? Dunno..

**Comment by ineiti** [comment]
Can you try adding:

```
go_import_path: gopkg.in/dedis/crypto.v0
```

to `travis.yml`? It did wonders for `onet.v1` ;)

**Pull request merged**
