### PR TITLE
Test exploring code

### PR DESCRIPTION
**Pull request by WEB3-GForce**
This is to go along with issue #35 . Feel free to use this to explore the issue.

### CODE REVIEW

**Comment by bford** [comment]
Aha - looks like you uncovered a bug in the crypto/edwards curve package, because changing the definition of 'group' to use either the crypto/nist or crypto/edwards/ed25519 implementations makes the test work fine.  I'm taking a closer look at that code.

**Comment by bford** [comment]
Aha, got it.  It even worked in the case of edwards.ProjectiveCurve (as the altGroup was using), but there was a bug in UnmarshalPoint for edwards.ExtendedCurve.  Please apply this fix to your branch:

```
--- a/edwards/ext.go
+++ b/edwards/ext.go
@@ -45,8 +45,12 @@ func (P *extPoint) MarshalBinary() ([]byte, error) {
 }
 
 func (P *extPoint) UnmarshalBinary(b []byte) error {
+       if err := P.c.decodePoint(b, &P.X, &P.Y); err != nil {
+               return err
+       }
        P.Z.Init64(1, &P.c.P)
-       return P.c.decodePoint(b, &P.X, &P.Y)
+       P.T.Mul(&P.X, &P.Y)
+       return nil
 }
```

Then, once you verify that this fixes the problem, can you clean up and pare down your polynomial encode/decode testing code into a more concise test that just systematically tests the relevant encode/decode functionality?

Thanks
Bryan

**Comment by WEB3-GForce** [comment]
That does it; the test cases pass. I will tidy up the test and then commit
them as well as the change to ext.go

On Tue, Feb 24, 2015 at 1:37 PM, Bryan Ford <notifications@github.com>
wrote:

> Aha, got it. It even worked in the case of edwards.ProjectiveCurve (as the
> altGroup was using), but there was a bug in UnmarshalPoint for
> edwards.ExtendedCurve. Please apply this fix to your branch:
>
> --- a/edwards/ext.go
> +++ b/edwards/ext.go
> @@ -45,8 +45,12 @@ func (P *extPoint) MarshalBinary() ([]byte, error) {
>  }
>
>  func (P *extPoint) UnmarshalBinary(b []byte) error {
> +       if err := P.c.decodePoint(b, &P.X, &P.Y); err != nil {
> +               return err
> +       }
>         P.Z.Init64(1, &P.c.P)
> -       return P.c.decodePoint(b, &P.X, &P.Y)
> +       P.T.Mul(&P.X, &P.Y)
> +       return nil
>  }
>
> Then, once you verify that this fixes the problem, can you clean up and
> pare down your polynomial encode/decode testing code into a more concise
> test that just systematically tests the relevant encode/decode
> functionality?
>
> Thanks
> Bryan
>
> —
> Reply to this email directly or view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_DeDiS_crypto_pull_39-23issuecomment-2D75817216&d=AwMCaQ&c=-dg2m7zWuuDZ0MUcV7Sdqw&r=GPxwT4fhhmVz-1RB6SMPpOGPGmZuqB1ZodgT3dSLWWI&m=FAFKfHIXyakaTu9VFIT6gaSrlGc8MYZoIs3V2SMLUPo&s=FF7Svq1rPI1MFDu81XYN0MdhPYDOAQ1jX6dXoDTrduw&e=>
> .
>



-- 
William Edward Bailey, III

**Comment by WEB3-GForce** [comment]
Patched and ready to go.

**Pull request merged**
